### ISSUE TITLE
Improve searching users

### ISSUE THREAD

**Issue by jcvanderwal** [isisaddons/isis-module-security#17]
It's difficult to find the users. Some suggestions:

Add:
- allUsers

Implement wildcard search on:
-findByUsername
-findByName

**Comment by danhaywood** [comment]
It turns out that there is already an ApplicationUsers#allUsers(), but it is marked as being prototype.  I've removed this to make it always available.  (Any given app can always suppress the action again either through security or by writing a vetoing subscriber).

Also, the findByName already supports wildcards, %x% to match any occurrence of 'x' in either the familyName, givenName or knownAs.
